### ISSUE TITLE
seems working

### ISSUE THREAD

**Issue by koji** [hannahtardie/icmfinal_updated#1]
@hannahtardie 
my mac
cpu 2.9 GHz Intel Core i7
os mojave
ram 16GB

![hannahtardie](https://user-images.githubusercontent.com/474225/49757075-82348800-fc89-11e8-8563-2965caf7f28d.gif)

Have you tried your sketch on a production laptop?

**Comment by hannahtardie** [comment]
@sleepy-maker ahhhh yes. this is what it should look like. i tried on a mac rented from the ER but i don't think it is a production laptop since it crashes around slide 4-5. this is perfect!
do you have any suggestions for next time about how to make it more accessible to computers w/ lower ram or is this not really possible if i want to have this many graphics ?

**Comment by koji** [comment]
I can't see the crash, so the followings are kind of general things to improve the performance.

https://github.com/hannahtardie/icmfinal_updated/blob/master/sketch.js#L80-L109

you can switch from `if-else` to `switch` statement.
switch is slightly faster than if-else.

```
switch(currentSlide) {
    case 0:
     // do something
     break;

    case 1:
     // do something
     break;

    default:
    break;
}
```

Also you can make canvas size smaller --> 400x400 or 500x500.


using html, css & js instead of p5domjs. i think p5dom doesn't use virtual dom(like reactjs), so it could make your program slow.


In terms of slide functions,
https://github.com/hannahtardie/icmfinal_updated/blob/master/sketch.js#L198
you could use loop instead of hardcoding


Finally, you can minimize your sketch.js with the following which means you can create sketch.mini.js.
https://javascript-minifier.com/
